name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.6 [CE|EE|ECE 2.4.0-2.4.7] 18 Feb 2025
          tag_name: 1.0.6
          body: |-
            Compatibility with [Optimised stock source assignment](https://github.com/softcommerceltd/mage2plenty-os/issues/48)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
